### ISSUE TITLE
[Request]: Fix typos on QASP page of de-risking guide

### ISSUE THREAD

**Issue by beechnut** [18F/guides#448]
### A description of the work

The [QASP page](https://guides.18f.gov/derisking/qasp/) has a table with a number of typos in many cells.

A couple examples:

- "...and a clean code baseVersion-controlled..." should probably be two lines
- "A system diagram is provided" cuts off, I suspect this should finish with something like "each release."

There might be more typos, but these were the ones I found.

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [X] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### How much time do you anticipate this work taking?

3 hours

### Acceptance Criteria

Typos are fixed, line breaks are placed appropriately.

**Comment by juliaklindpaintner** [comment]
Note: The first of the two typos is addressed in #455

**Comment by amandarkennedy** [comment]
@juliaklindpaintner can you clarify your above comment?  I am still seeing both issues in the [Sample QASP](https://guides.18f.gov/derisking/qasp/).

> Note: The first of the two typos is addressed in #455

**Comment by juliaklindpaintner** [comment]
Sorry, @amandarkennedy. I got a little mixed up. I ended up deleting #455 in favor of this ticket. I have already made an update, but [the PR isn't merged yet](https://github.com/18F/guides/pull/457), because I wanted to wait and add the other fix so we could just do one PR together. You're right that both issues are still there on the live site. 

Re: the second issue, I took a look at the print version of the guides, and it doesn't appear that any other copy is missing. Perhaps we just add a period to the end of these so that it doesn't seem cut off?

**Comment by amandarkennedy** [comment]
@juliaklindpaintner Gotcha, no worries! 

Re: the second issue, I know what you mean. I have noticed at 18F, though, that our typical "style" is to not include a period at the end of a sentence in a table or within a bullet point. Would you say that is the case?

**Comment by juliaklindpaintner** [comment]
@amandarkennedy Here's the [guidance around punctuation in the Content Guide](https://guides.18f.gov/content-guide/our-style/punctuation/#bulleted-lists). In this instance, it's in sentence form, so I think a period makes sense. We can also talk about whether we should include line breaks to make it more like bullet points. I think we can make a call on what seems clearest.

**Comment by amandarkennedy** [comment]
@juliaklindpaintner oooh, thank you. perfect! looking forward to talking more.

**Comment by juliaklindpaintner** [comment]
[Done and updated](https://guides.18f.gov/derisking/qasp/)!
